#  Template Java Spring Boot App for Elastic Beanstalk

#  This template allows you to deploy your application as code using AWS Elastic Beanstalk.
#  The workflow allows validate, linting and security scans on feature branches (as well as master).
#  The Spring Boot App will be validated and deployed after the code is merged to master.

# Prerequisites: $AWS_ACCESS_KEY_ID, $AWS_SECRET_ACCESS_KEY, $AWS_DEFAULT_REGION setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/atlassian/aws-elasticbeanstalk-deploy/src/master/README.md



image: gradle:6.7.0-jdk11

pipelines:
  branches:
    master:
      - step:
          name: Build frontend
          image: node:10.15.3
          script:
            - cd frontend_sources
            - npm install
            - npm run build
      - step:
          name: Build and Test
          caches:
            - gradle
          script:
            - gradle build
          artifacts: 
            - 'raritycheck.jar'
      - step:
          name: Deploy to staging
          deployment: Raritycheck-env
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.7.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "eu-central-1"
                COMMAND: 'all'
                ENVIRONMENT_NAME: "Raritycheck-env"
                APPLICATION_NAME: "RarityCheck"
                ZIP_FILE: "raritycheck.jar"
                S3_BUCKET: 'elasticbeanstalk-eu-central-1-916378583184'
