const APP_UPDATE_INTERVAL = 180000;

export const SUBCATEGORIES_UPDATE_INTERVAL = APP_UPDATE_INTERVAL;
export const CATEGORIES_UPDATE_INTERVAL = APP_UPDATE_INTERVAL;
export const ITEMS_UPDATE_INTERVAL = APP_UPDATE_INTERVAL;

export const TOKEN_REFRESH_INTERVAL = 3300000;
